server.port=8086
spring.application.name=messaging-service

spring.datasource.url=jdbc:postgresql://localhost:5432/libro_clases
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
